name = "data-share"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# KV ネームスペース（デプロイ前に作成して ID を埋める）
[[kv_namespaces]]
binding = "KV"
id = "348a89215cab42939b76044f24b996ff"

[[r2_buckets]]
binding = "R2"
bucket_name = "data-share-files"

[triggers]
crons = ["* * * * *"]
